# Copyright 2026 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.
name = "wasm-pack"
type = "cli"

[resolve]
git-url = "https://github.com/rustwasm/wasm-pack"

[platform.linux]
archive-prefix = "wasm-pack-v{version}-{arch}-unknown-linux-musl"
exe-path = "wasm-pack"
download-file = "wasm-pack-v{version}-{arch}-unknown-linux-musl.tar.gz"

[platform.macos]
archive-prefix = "wasm-pack-v{version}-{arch}-apple-darwin"
exe-path = "wasm-pack"
download-file = "wasm-pack-v{version}-{arch}-apple-darwin.tar.gz"

[platform.windows]
archive-prefix = "wasm-pack-v{version}-x86_64-pc-windows-msvc"
exe-path = "wasm-pack.exe"
download-file = "wasm-pack-v{version}-x86_64-pc-windows-msvc.tar.gz"

[install]
download-url = "https://github.com/rustwasm/wasm-pack/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "aarch64"
x86_64 = "x86_64"

[install.exes.wasm-pack]
exe-path = "wasm-pack"
primary = true
