// Copyright 2026 Adobe. All rights reserved.
// This file is licensed to you under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may obtain a copy
// of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under
// the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
// OF ANY KIND, either express or implied. See the License for the specific language
// governing permissions and limitations under the License.

//! Design system registry data embedded at compile time.
//!
//! Registry JSON files are embedded via the generated `registry_data.rs` (run
//! `moon run sdk:codegen` to regenerate). The set of embedded registries and the
//! list of SPEC-009 advisory fields are both driven by the field catalog in
//! `packages/design-data-spec/fields/` — no Rust changes needed when adding a field.

use std::collections::{HashMap, HashSet};

use serde_json::Value;

/// Parsed registry data for SPEC-009 enum validation.
///
/// Keyed by field name (e.g. `"component"`, `"state"`). Built from the
/// field catalog declarations in `packages/design-data-spec/fields/` via
/// the generated `build_registry_map()` function in `registry_data.rs`.
#[derive(Debug, Clone)]
pub struct RegistryData {
    registries: HashMap<String, HashSet<String>>,
}

/// Parse a registry JSON file into a set of value IDs (and their aliases).
fn parse_registry(json_str: &str) -> HashSet<String> {
    let v: Value = serde_json::from_str(json_str).expect("embedded registry JSON must be valid");
    let mut set = HashSet::new();
    if let Some(values) = v.get("values").and_then(|v| v.as_array()) {
        for entry in values {
            if let Some(id) = entry.get("id").and_then(|v| v.as_str()) {
                set.insert(id.to_string());
            }
            if let Some(aliases) = entry.get("aliases").and_then(|v| v.as_array()) {
                for alias in aliases {
                    if let Some(a) = alias.as_str() {
                        set.insert(a.to_string());
                    }
                }
            }
        }
    }
    set
}

// Generated by scripts/generate-registry-data.js from the field catalog and
// registry JSON files. Checked into git so the crate is self-contained.
// Regenerate with: moon run sdk:codegen
include!("registry_data.rs");

impl RegistryData {
    /// Build registry data from the embedded JSON constants in `registry_data.rs`.
    ///
    /// `registry_data.rs` is generated from `packages/design-data-spec/fields/`
    /// (field catalog) and `packages/design-system-registry/registry/` (vocabulary)
    /// by running `moon run sdk:codegen`. Adding a new field declaration and
    /// re-running codegen is all that's needed to extend SPEC-009.
    pub fn embedded() -> Self {
        Self {
            registries: build_registry_map(),
        }
    }

    /// Look up the vocabulary set for a name-object field.
    /// Returns `None` for fields without a registry (e.g. `property`, mode-set fields).
    pub fn for_field(&self, field: &str) -> Option<&HashSet<String>> {
        self.registries.get(field)
    }

    /// The set of semantic fields that SPEC-009 checks against their registry.
    /// Derived from field declarations with `validation: "advisory"` and a registry.
    pub fn advisory_fields(&self) -> &[&str] {
        FIELD_ADVISORY_FIELDS
    }

    /// The set of valid component category ids from the categories registry.
    /// Used by SPEC-034 to validate `meta.category` on component declarations.
    pub fn categories(&self) -> &HashSet<String> {
        self.registries
            .get("categories")
            .expect("categories registry is always embedded")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_registries_load() {
        let r = RegistryData::embedded();
        assert!(r.for_field("component").unwrap().contains("button"));
        assert!(r.for_field("state").unwrap().contains("hover"));
        assert!(r.for_field("variant").unwrap().contains("accent"));
        assert!(r.for_field("size").unwrap().contains("m"));
        assert!(r.for_field("anatomy").unwrap().contains("icon"));
        assert!(r.for_field("object").unwrap().contains("background"));
        assert!(r.for_field("structure").unwrap().contains("base"));
        assert!(r.for_field("orientation").unwrap().contains("vertical"));
        assert!(r.for_field("position").unwrap().contains("top"));
        assert!(r.for_field("density").unwrap().contains("compact"));
        assert!(r.for_field("shape").unwrap().contains("uniform"));
    }

    #[test]
    fn sizes_excludes_numeric_scale() {
        let r = RegistryData::embedded();
        let sizes = r.for_field("size").unwrap();
        assert!(!sizes.contains("50"));
        assert!(!sizes.contains("100"));
        assert!(!sizes.contains("200"));
    }

    #[test]
    fn for_field_returns_correct_registry() {
        let r = RegistryData::embedded();
        assert!(r.for_field("component").unwrap().contains("button"));
        assert!(r.for_field("object").unwrap().contains("background"));
        assert!(r.for_field("property").unwrap().contains("color")); // advisory registry
        assert!(r.for_field("colorScheme").is_none()); // mode-set, validated by SPEC-005/008
    }

    #[test]
    fn advisory_fields_matches_catalog() {
        let r = RegistryData::embedded();
        let fields = r.advisory_fields();
        // All advisory fields must have a backing registry
        for &field in fields {
            assert!(
                r.for_field(field).is_some(),
                "advisory field '{field}' has no registry"
            );
        }
        // The expected set from the field catalog
        assert!(fields.contains(&"component"));
        assert!(fields.contains(&"state"));
        assert!(fields.contains(&"variant"));
        assert!(fields.contains(&"size"));
        assert!(fields.contains(&"property")); // advisory registry added in #941
        // mode-set fields must not appear
        assert!(!fields.contains(&"colorScheme"));
        assert!(!fields.contains(&"scale"));
        assert!(!fields.contains(&"contrast"));
    }
}
