// @generated by scripts/generate-registry-data.js
// Sources: packages/design-data-spec/fields/*.json → packages/design-system-registry/registry/*.json
// Do not edit manually — run `moon run sdk:codegen` to regenerate.

const VARIANTS_JSON: &str = r##"{
  "$schema": "https://opensource.adobe.com/spectrum-design-data/schemas/registry-value.json",
  "type": "variant",
  "description": "Color and style variants used across components",
  "values": [
    {
      "id": "accent",
      "label": "Accent",
      "description": "Primary accent color variant",
      "category": "emphasis",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "negative",
      "label": "Negative",
      "description": "Destructive or negative action variant",
      "category": "semantic",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "primary",
      "label": "Primary",
      "description": "Primary emphasis variant",
      "category": "emphasis",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "secondary",
      "label": "Secondary",
      "description": "Secondary emphasis variant",
      "category": "emphasis",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "positive",
      "label": "Positive",
      "description": "Affirmative or positive action variant",
      "category": "semantic",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "notice",
      "label": "Notice",
      "description": "Notice or attention variant",
      "category": "semantic",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "informative",
      "label": "Informative",
      "description": "Informational variant",
      "category": "semantic",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "neutral",
      "label": "Neutral",
      "description": "Neutral variant",
      "category": "semantic",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "gray",
      "label": "Gray",
      "description": "Gray color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "red",
      "label": "Red",
      "description": "Red color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "orange",
      "label": "Orange",
      "description": "Orange color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "yellow",
      "label": "Yellow",
      "description": "Yellow color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "chartreuse",
      "label": "Chartreuse",
      "description": "Chartreuse color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "celery",
      "label": "Celery",
      "description": "Celery color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "green",
      "label": "Green",
      "description": "Green color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "seafoam",
      "label": "Seafoam",
      "description": "Seafoam color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "cyan",
      "label": "Cyan",
      "description": "Cyan color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "blue",
      "label": "Blue",
      "description": "Blue color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "indigo",
      "label": "Indigo",
      "description": "Indigo color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "purple",
      "label": "Purple",
      "description": "Purple color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "fuchsia",
      "label": "Fuchsia",
      "description": "Fuchsia color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "magenta",
      "label": "Magenta",
      "description": "Magenta color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "pink",
      "label": "Pink",
      "description": "Pink color variant",
      "category": "color",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "over-background",
      "label": "Over Background",
      "aliases": ["over background"],
      "description": "Designed to be used over backgrounds",
      "category": "context",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "brown",
      "label": "Brown",
      "description": "Brown color variant",
      "category": "color",
      "usedIn": ["tokens"]
    },
    {
      "id": "cinnamon",
      "label": "Cinnamon",
      "description": "Cinnamon color variant",
      "category": "color",
      "usedIn": ["tokens"]
    },
    {
      "id": "silver",
      "label": "Silver",
      "description": "Silver color variant",
      "category": "color",
      "usedIn": ["tokens"]
    },
    {
      "id": "subtle",
      "label": "Subtle",
      "description": "Reduced emphasis variant for less prominent surfaces",
      "category": "emphasis",
      "usedIn": ["tokens"]
    },
    {
      "id": "subdued",
      "label": "Subdued",
      "description": "Lower emphasis variant for quieter backgrounds",
      "category": "emphasis",
      "usedIn": ["tokens"]
    },
    {
      "id": "static",
      "label": "Static",
      "description": "Context variant indicating the token does not change with theme",
      "category": "context",
      "usedIn": ["tokens"]
    },
    {
      "id": "inverse",
      "label": "Inverse",
      "description": "Inverted color context variant",
      "category": "context",
      "usedIn": ["tokens"]
    },
    {
      "id": "black",
      "label": "Black",
      "description": "Black color modifier, typically used with static context",
      "category": "color",
      "usedIn": ["tokens"]
    },
    {
      "id": "white",
      "label": "White",
      "description": "White color modifier, typically used with static context",
      "category": "color",
      "usedIn": ["tokens"]
    },
    {
      "id": "turquoise",
      "label": "Turquoise",
      "description": "Turquoise color variant",
      "category": "color",
      "usedIn": ["tokens"]
    },
    {
      "id": "confirmation",
      "label": "Confirmation",
      "description": "Confirmation dialog variant requiring user acknowledgement",
      "category": "semantic",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "destructive",
      "label": "Destructive",
      "description": "Destructive action dialog variant (stronger than negative)",
      "category": "semantic",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "warning",
      "label": "Warning",
      "description": "Warning dialog variant for cautionary alerts",
      "category": "semantic",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "error",
      "label": "Error",
      "description": "Error state variant for failed operations",
      "category": "semantic",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "information",
      "label": "Information",
      "aliases": ["info"],
      "description": "Informational dialog variant (alias for informative in alert contexts)",
      "category": "semantic",
      "usedIn": ["component-schemas"]
    }
  ]
}
"##;
const COMPONENTS_JSON: &str = r##"{
  "$schema": "https://opensource.adobe.com/spectrum-design-data/schemas/registry-value.json",
  "type": "component",
  "description": "Spectrum component names",
  "values": [
    {
      "id": "accordion",
      "label": "Accordion",
      "documentationUrl": "https://spectrum.adobe.com/page/accordion/"
    },
    {
      "id": "action-bar",
      "label": "Action Bar",
      "documentationUrl": "https://spectrum.adobe.com/page/action-bar/"
    },
    {
      "id": "action-button",
      "label": "Action Button",
      "documentationUrl": "https://spectrum.adobe.com/page/action-button/"
    },
    {
      "id": "action-group",
      "label": "Action Group",
      "documentationUrl": "https://spectrum.adobe.com/page/action-group/"
    },
    {
      "id": "alert-banner",
      "label": "Alert Banner",
      "documentationUrl": "https://spectrum.adobe.com/page/alert-banner/"
    },
    {
      "id": "alert-dialog",
      "label": "Alert Dialog",
      "documentationUrl": "https://spectrum.adobe.com/page/alert-dialog/"
    },
    {
      "id": "avatar",
      "label": "Avatar",
      "documentationUrl": "https://spectrum.adobe.com/page/avatar/"
    },
    {
      "id": "avatar-group",
      "label": "Avatar Group",
      "documentationUrl": "https://spectrum.adobe.com/page/avatar-group/"
    },
    {
      "id": "badge",
      "label": "Badge",
      "documentationUrl": "https://spectrum.adobe.com/page/badge/"
    },
    {
      "id": "breadcrumbs",
      "label": "Breadcrumbs",
      "documentationUrl": "https://spectrum.adobe.com/page/breadcrumbs/"
    },
    {
      "id": "button",
      "label": "Button",
      "documentationUrl": "https://spectrum.adobe.com/page/button/"
    },
    {
      "id": "button-group",
      "label": "Button Group",
      "documentationUrl": "https://spectrum.adobe.com/page/button-group/"
    },
    {
      "id": "calendar",
      "label": "Calendar",
      "documentationUrl": "https://spectrum.adobe.com/page/calendar/"
    },
    {
      "id": "checkbox",
      "label": "Checkbox",
      "documentationUrl": "https://spectrum.adobe.com/page/checkbox/"
    },
    {
      "id": "checkbox-group",
      "label": "Checkbox Group",
      "documentationUrl": "https://spectrum.adobe.com/page/checkbox-group/"
    },
    {
      "id": "close-button",
      "label": "Close Button",
      "documentationUrl": "https://spectrum.adobe.com/page/close-button/"
    },
    {
      "id": "color-area",
      "label": "Color Area",
      "documentationUrl": "https://spectrum.adobe.com/page/color-area/"
    },
    {
      "id": "color-slider",
      "label": "Color Slider",
      "documentationUrl": "https://spectrum.adobe.com/page/color-slider/"
    },
    {
      "id": "color-wheel",
      "label": "Color Wheel",
      "documentationUrl": "https://spectrum.adobe.com/page/color-wheel/"
    },
    {
      "id": "combo-box",
      "label": "Combo Box",
      "documentationUrl": "https://spectrum.adobe.com/page/combo-box/"
    },
    {
      "id": "contextual-help",
      "label": "Contextual Help",
      "documentationUrl": "https://spectrum.adobe.com/page/contextual-help/"
    },
    {
      "id": "date-picker",
      "label": "Date Picker",
      "documentationUrl": "https://spectrum.adobe.com/page/date-picker/"
    },
    {
      "id": "divider",
      "label": "Divider",
      "documentationUrl": "https://spectrum.adobe.com/page/divider/"
    },
    {
      "id": "drop-zone",
      "label": "Drop Zone",
      "documentationUrl": "https://spectrum.adobe.com/page/drop-zone/"
    },
    {
      "id": "field-label",
      "label": "Field Label",
      "documentationUrl": "https://spectrum.adobe.com/page/field-label/"
    },
    {
      "id": "help-text",
      "label": "Help Text",
      "documentationUrl": "https://spectrum.adobe.com/page/help-text/"
    },
    {
      "id": "illustrated-message",
      "label": "Illustrated Message",
      "documentationUrl": "https://spectrum.adobe.com/page/illustrated-message/"
    },
    {
      "id": "in-line-alert",
      "label": "In-Line Alert",
      "documentationUrl": "https://spectrum.adobe.com/page/in-line-alert/"
    },
    {
      "id": "link",
      "label": "Link",
      "documentationUrl": "https://spectrum.adobe.com/page/link/"
    },
    {
      "id": "menu",
      "label": "Menu",
      "documentationUrl": "https://spectrum.adobe.com/page/menu/"
    },
    {
      "id": "meter",
      "label": "Meter",
      "documentationUrl": "https://spectrum.adobe.com/page/meter/"
    },
    {
      "id": "number-field",
      "label": "Number Field",
      "documentationUrl": "https://spectrum.adobe.com/page/number-field/"
    },
    {
      "id": "picker",
      "label": "Picker",
      "documentationUrl": "https://spectrum.adobe.com/page/picker/"
    },
    {
      "id": "popover",
      "label": "Popover",
      "documentationUrl": "https://spectrum.adobe.com/page/popover/"
    },
    {
      "id": "progress-bar",
      "label": "Progress Bar",
      "documentationUrl": "https://spectrum.adobe.com/page/progress-bar/"
    },
    {
      "id": "progress-circle",
      "label": "Progress Circle",
      "documentationUrl": "https://spectrum.adobe.com/page/progress-circle/"
    },
    {
      "id": "radio-button",
      "label": "Radio Button",
      "documentationUrl": "https://spectrum.adobe.com/page/radio-button/"
    },
    {
      "id": "radio-group",
      "label": "Radio Group",
      "documentationUrl": "https://spectrum.adobe.com/page/radio-group/"
    },
    {
      "id": "rating",
      "label": "Rating",
      "documentationUrl": "https://spectrum.adobe.com/page/rating/"
    },
    {
      "id": "search-field",
      "label": "Search Field",
      "documentationUrl": "https://spectrum.adobe.com/page/search-field/"
    },
    {
      "id": "select-box",
      "label": "Select Box",
      "documentationUrl": "https://spectrum.adobe.com/page/select-box/"
    },
    {
      "id": "slider",
      "label": "Slider",
      "documentationUrl": "https://spectrum.adobe.com/page/slider/"
    },
    {
      "id": "status-light",
      "label": "Status Light",
      "documentationUrl": "https://spectrum.adobe.com/page/status-light/"
    },
    {
      "id": "swatch",
      "label": "Swatch",
      "documentationUrl": "https://spectrum.adobe.com/page/swatch/"
    },
    {
      "id": "switch",
      "label": "Switch",
      "documentationUrl": "https://spectrum.adobe.com/page/switch/"
    },
    {
      "id": "table",
      "label": "Table",
      "documentationUrl": "https://spectrum.adobe.com/page/table/"
    },
    {
      "id": "tabs",
      "label": "Tabs",
      "documentationUrl": "https://spectrum.adobe.com/page/tabs/"
    },
    {
      "id": "tag",
      "label": "Tag",
      "documentationUrl": "https://spectrum.adobe.com/page/tag/"
    },
    {
      "id": "tag-group",
      "label": "Tag Group",
      "documentationUrl": "https://spectrum.adobe.com/page/tag-group/"
    },
    {
      "id": "text-area",
      "label": "Text Area",
      "documentationUrl": "https://spectrum.adobe.com/page/text-area/"
    },
    {
      "id": "text-field",
      "label": "Text Field",
      "documentationUrl": "https://spectrum.adobe.com/page/text-field/"
    },
    {
      "id": "toast",
      "label": "Toast",
      "documentationUrl": "https://spectrum.adobe.com/page/toast/"
    },
    {
      "id": "tooltip",
      "label": "Tooltip",
      "documentationUrl": "https://spectrum.adobe.com/page/tooltip/"
    },
    {
      "id": "tray",
      "label": "Tray",
      "documentationUrl": "https://spectrum.adobe.com/page/tray/"
    }
  ]
}
"##;
const STRUCTURES_JSON: &str = r##"{
  "$schema": "https://opensource.adobe.com/spectrum-design-data/schemas/registry-value.json",
  "type": "structure",
  "description": "Reusable visual patterns or object categories that occur across many varieties of components. Distinct from components, which are specific UI elements.",
  "values": [
    {
      "id": "base",
      "label": "Base",
      "description": "Foundation structure shared across components"
    },
    {
      "id": "container",
      "label": "Container",
      "description": "Enclosing structure that holds child elements"
    },
    {
      "id": "list",
      "label": "List",
      "description": "Ordered or unordered collection of items"
    },
    {
      "id": "accessory",
      "label": "Accessory",
      "description": "Supplementary element attached to a primary structure"
    }
  ]
}
"##;
const SUBSTRUCTURES_JSON: &str = r##"{
  "$schema": "https://opensource.adobe.com/spectrum-design-data/schemas/registry-value.json",
  "type": "substructure",
  "description": "Structures that only exist within the context of a parent structure (e.g., item within a list).",
  "values": [
    {
      "id": "item",
      "label": "Item",
      "description": "Individual element within a parent structure (e.g., list item)"
    }
  ]
}
"##;
const ANATOMY_TERMS_JSON: &str = r##"{
  "$schema": "https://opensource.adobe.com/spectrum-design-data/schemas/registry-value.json",
  "type": "anatomy-term",
  "description": "Visible, named parts of components as defined by designers. These are the parts called out in component specification diagrams. Styling surfaces (background, border, etc.) belong in token-objects.json; positional terms (top, bottom, etc.) belong in positions.json.",
  "values": [
    {
      "id": "text",
      "label": "Text",
      "description": "Text content or labels",
      "usedIn": ["tokens"]
    },
    {
      "id": "control",
      "label": "Control",
      "description": "Interactive control elements like checkboxes or radio buttons",
      "usedIn": ["tokens"]
    },
    {
      "id": "icon",
      "label": "Icon",
      "description": "Icon elements",
      "usedIn": ["tokens", "component-schemas"]
    },
    {
      "id": "label",
      "label": "Label",
      "description": "Text labels",
      "usedIn": ["tokens", "component-schemas"]
    },
    {
      "id": "body",
      "label": "Body",
      "description": "Main body or content container",
      "usedIn": ["tokens"]
    },
    {
      "id": "header",
      "label": "Header",
      "description": "Header section",
      "usedIn": ["tokens"]
    },
    {
      "id": "footer",
      "label": "Footer",
      "description": "Footer section",
      "usedIn": ["tokens"]
    },
    {
      "id": "divider",
      "label": "Divider",
      "description": "Dividing line or separator",
      "usedIn": ["tokens"]
    },
    {
      "id": "handle",
      "label": "Handle",
      "description": "Draggable handle element",
      "usedIn": ["tokens"]
    },
    {
      "id": "indicator",
      "label": "Indicator",
      "description": "Visual indicator or marker",
      "usedIn": ["tokens"]
    },
    {
      "id": "track",
      "label": "Track",
      "description": "Track or rail element (e.g., in sliders)",
      "usedIn": ["tokens"]
    },
    {
      "id": "thumb",
      "label": "Thumb",
      "description": "Draggable thumb element (e.g., in sliders)",
      "usedIn": ["tokens"]
    },
    {
      "id": "avatar",
      "label": "Avatar",
      "description": "User avatar or profile image",
      "usedIn": ["tokens"]
    },
    {
      "id": "badge",
      "label": "Badge",
      "description": "Badge or notification indicator",
      "usedIn": ["tokens"]
    },
    {
      "id": "pill",
      "label": "Pill",
      "description": "Pill-shaped element",
      "usedIn": ["tokens"]
    },
    {
      "id": "title",
      "label": "Title",
      "description": "Title text element within a component",
      "usedIn": ["tokens"]
    },
    {
      "id": "description",
      "label": "Description",
      "description": "Descriptive text element within a component",
      "usedIn": ["tokens"]
    },
    {
      "id": "row",
      "label": "Row",
      "description": "Table or list row element",
      "usedIn": ["tokens"]
    },
    {
      "id": "step",
      "label": "Step",
      "description": "Individual step element in a step list or wizard",
      "usedIn": ["tokens"]
    },
    {
      "id": "counter",
      "label": "Counter",
      "description": "Numeric counter or badge element",
      "usedIn": ["tokens"]
    },
    {
      "id": "preview",
      "label": "Preview",
      "description": "Preview area or thumbnail within a component",
      "usedIn": ["tokens"]
    },
    {
      "id": "tip",
      "label": "Tip",
      "description": "Tooltip tip or arrow element",
      "usedIn": ["tokens"]
    },
    {
      "id": "selection",
      "label": "Selection",
      "description": "Selection indicator or highlight element",
      "usedIn": ["tokens"]
    },
    {
      "id": "media",
      "label": "Media",
      "description": "Media container (image, video) within a component",
      "usedIn": ["tokens"]
    },
    {
      "id": "ring",
      "label": "Ring",
      "description": "Focus ring or outline indicator",
      "usedIn": ["tokens"]
    },
    {
      "id": "field",
      "label": "Field",
      "description": "Input container element in form components (text-field, number-field, combo-box, picker, etc.)",
      "usedIn": ["tokens", "s2-docs"]
    },
    {
      "id": "fill",
      "label": "Fill",
      "description": "Active/completed portion of a track-based component (slider, meter, progress-bar, progress-circle)",
      "usedIn": ["tokens", "s2-docs"]
    },
    {
      "id": "value",
      "label": "Value",
      "description": "Displayed data value within a component (numeric readout, selected text, menu item value)",
      "usedIn": ["tokens", "s2-docs"]
    },
    {
      "id": "container",
      "label": "Container",
      "description": "Outer wrapper element of a component (cards, swatch, thumbnail, avatar)",
      "usedIn": ["tokens", "s2-docs"]
    },
    {
      "id": "chevron",
      "label": "Chevron",
      "description": "Directional arrow indicator (disclosure, navigation, drill-in)",
      "usedIn": ["tokens", "s2-docs"]
    },
    {
      "id": "loupe",
      "label": "Loupe",
      "description": "Magnified color preview element in color components (color-area, color-slider, color-wheel)",
      "usedIn": ["tokens", "s2-docs"]
    },
    {
      "id": "dot",
      "label": "Dot",
      "description": "Small circular indicator element (status-light)",
      "usedIn": ["tokens", "s2-docs"]
    },
    {
      "id": "separator",
      "label": "Separator",
      "description": "Visual separator between items (breadcrumbs)",
      "usedIn": ["tokens", "s2-docs"]
    },
    {
      "id": "checkmark",
      "label": "Checkmark",
      "description": "Check or confirmation icon element within a component",
      "usedIn": ["tokens"]
    },
    {
      "id": "stepper",
      "label": "Stepper",
      "description": "Increment/decrement control in number-field",
      "usedIn": ["tokens", "s2-docs"]
    },
    {
      "id": "area",
      "label": "Area",
      "description": "Interactive surface region (color-area gradient surface)",
      "usedIn": ["tokens", "s2-docs"]
    },
    {
      "id": "gripper",
      "label": "Gripper",
      "description": "Draggable resize handle element (standard-panel)",
      "usedIn": ["tokens", "s2-docs"]
    },
    {
      "id": "illustration",
      "label": "Illustration",
      "description": "Decorative or explanatory illustration within a component",
      "usedIn": ["tokens", "s2-docs"]
    },
    {
      "id": "heading",
      "label": "Heading",
      "description": "Heading text element within a component section",
      "usedIn": ["tokens", "s2-docs"]
    },
    {
      "id": "focus-ring",
      "label": "Focus Ring",
      "description": "Visible ring drawn around a focused component for accessibility",
      "usedIn": ["tokens"]
    },
    {
      "id": "focus-indicator",
      "label": "Focus Indicator",
      "description": "Visual indicator showing keyboard focus state on a component",
      "usedIn": ["tokens"]
    },
    {
      "id": "workflow-icon",
      "label": "Workflow Icon",
      "description": "Standard workflow icon element within a component (distinct from UI icons)",
      "usedIn": ["tokens", "s2-docs"]
    },
    {
      "id": "ui-icon",
      "label": "UI Icon",
      "description": "System UI icon element (chevrons, checkmarks, close icons) within a component",
      "usedIn": ["tokens"]
    }
  ]
}
"##;
const TOKEN_OBJECTS_JSON: &str = r##"{
  "$schema": "https://opensource.adobe.com/spectrum-design-data/schemas/registry-value.json",
  "type": "token-object",
  "description": "Styling surfaces to which visual properties are applied. These are abstract targets that exist on any element regardless of component type. Not to be confused with component anatomy (visible named parts).",
  "values": [
    {
      "id": "background",
      "label": "Background",
      "description": "Background surface or fill"
    },
    {
      "id": "border",
      "label": "Border",
      "description": "Border or outline of a component"
    },
    {
      "id": "edge",
      "label": "Edge",
      "description": "Outer boundary of a component (used in spacing tokens)"
    },
    {
      "id": "visual",
      "label": "Visual",
      "description": "Visible graphic element area (may be inset from edge)"
    },
    {
      "id": "content",
      "label": "Content",
      "description": "Main content area"
    }
  ]
}
"##;
const ORIENTATIONS_JSON: &str = r##"{
  "$schema": "https://opensource.adobe.com/spectrum-design-data/schemas/registry-value.json",
  "type": "orientation",
  "description": "Direction or order of structures and elements within a component or pattern.",
  "values": [
    {
      "id": "vertical",
      "label": "Vertical",
      "description": "Top-to-bottom direction"
    },
    {
      "id": "horizontal",
      "label": "Horizontal",
      "description": "Left-to-right (or right-to-left) direction"
    }
  ]
}
"##;
const POSITIONS_JSON: &str = r##"{
  "$schema": "https://opensource.adobe.com/spectrum-design-data/schemas/registry-value.json",
  "type": "position",
  "description": "Location of an object relative to another, with or without respect to directional order.",
  "values": [
    {
      "id": "affixed",
      "label": "Affixed",
      "description": "Attached to another element in a fixed position"
    },
    {
      "id": "top",
      "label": "Top",
      "description": "Top position relative to a reference element"
    },
    {
      "id": "bottom",
      "label": "Bottom",
      "description": "Bottom position relative to a reference element"
    },
    {
      "id": "start",
      "label": "Start",
      "description": "Start position (left in LTR, right in RTL)"
    },
    {
      "id": "end",
      "label": "End",
      "description": "End position (right in LTR, left in RTL)"
    }
  ]
}
"##;
const SIZES_JSON: &str = r##"{
  "$schema": "https://opensource.adobe.com/spectrum-design-data/schemas/registry-value.json",
  "type": "size",
  "description": "Semantic t-shirt size values used across Spectrum. Numeric scale values belong in scale-values.json.",
  "values": [
    {
      "id": "xxxs",
      "label": "3X Small",
      "aliases": ["3x-small"],
      "tokenName": "3x-small",
      "usedIn": ["tokens"]
    },
    {
      "id": "xxs",
      "label": "2X Small",
      "aliases": ["2x-small"],
      "tokenName": "2x-small",
      "usedIn": ["tokens"]
    },
    {
      "id": "xs",
      "label": "Extra Small",
      "aliases": ["extra-small"],
      "tokenName": "extra-small",
      "usedIn": ["tokens", "component-options", "component-schemas"]
    },
    {
      "id": "s",
      "label": "Small",
      "aliases": ["small"],
      "tokenName": "small",
      "usedIn": ["tokens", "component-options", "component-schemas"]
    },
    {
      "id": "m",
      "label": "Medium",
      "aliases": ["medium"],
      "tokenName": "medium",
      "default": true,
      "usedIn": ["tokens", "component-options", "component-schemas"]
    },
    {
      "id": "l",
      "label": "Large",
      "aliases": ["large"],
      "tokenName": "large",
      "usedIn": ["tokens", "component-options", "component-schemas"]
    },
    {
      "id": "xl",
      "label": "Extra Large",
      "aliases": ["extra-large"],
      "tokenName": "extra-large",
      "usedIn": ["tokens", "component-options", "component-schemas"]
    },
    {
      "id": "xxl",
      "label": "2X Large",
      "aliases": ["2x-large"],
      "tokenName": "2x-large",
      "usedIn": ["tokens", "component-options", "component-schemas"]
    },
    {
      "id": "xxxl",
      "label": "3X Large",
      "aliases": ["3x-large"],
      "tokenName": "3x-large",
      "usedIn": ["tokens", "component-options", "component-schemas"]
    }
  ]
}
"##;
const DENSITIES_JSON: &str = r##"{
  "$schema": "https://opensource.adobe.com/spectrum-design-data/schemas/registry-value.json",
  "type": "density",
  "description": "Options that create more or less space within or around the parts of a component.",
  "values": [
    {
      "id": "spacious",
      "label": "Spacious",
      "description": "More space within and around component parts"
    },
    {
      "id": "compact",
      "label": "Compact",
      "description": "Less space within and around component parts"
    }
  ]
}
"##;
const SHAPES_JSON: &str = r##"{
  "$schema": "https://opensource.adobe.com/spectrum-design-data/schemas/registry-value.json",
  "type": "shape",
  "description": "Terms relative to the overall shape of a component. This is a starting vocabulary — new shape terms should be added here as design system patterns are identified.",
  "values": [
    {
      "id": "uniform",
      "label": "Uniform",
      "description": "Equal proportions (e.g., 1:1 ratio between horizontal and vertical padding)"
    }
  ]
}
"##;
const STATES_JSON: &str = r##"{
  "$schema": "https://opensource.adobe.com/spectrum-design-data/schemas/registry-value.json",
  "type": "state",
  "description": "Interaction states for components",
  "allowCustom": true,
  "customPattern": "^[a-z][a-z0-9-]*(\\s\\+\\s[a-z][a-z0-9-]*)*$",
  "values": [
    {
      "id": "default",
      "label": "Default",
      "description": "The default, resting state of a component",
      "default": true,
      "usedIn": ["tokens", "component-options", "component-schemas"],
      "definition": {
        "superordinate": "interaction state",
        "description": "The initial, resting state of a user interface component before any user interaction occurs",
        "essentialCharacteristics": [
          "Represents the component's appearance without user interaction",
          "The baseline state from which all other states transition",
          "Should communicate the component's purpose and interactivity at a glance"
        ]
      },
      "terminology": {
        "conceptType": "term",
        "namingRationale": "Industry-standard term used consistently across design systems and platforms"
      },
      "sources": [
        {
          "type": "industry-standard",
          "reference": "Common UI design terminology",
          "date": "2025-01-12"
        }
      ],
      "governance": {
        "owner": "Spectrum Core Team",
        "reviewDate": "2025-01-12",
        "status": "approved"
      },
      "relatedTerms": ["hover", "focus", "disabled"]
    },
    {
      "id": "hover",
      "label": "Hover",
      "description": "Mouse hover state",
      "usedIn": ["tokens", "component-options", "component-schemas"],
      "definition": {
        "superordinate": "interaction state",
        "description": "The state when a pointer device (such as a mouse cursor) is positioned over a component's interactive area without pressing",
        "essentialCharacteristics": [
          "Triggered by pointer positioning, not by clicking or pressing",
          "Provides visual feedback that the element is interactive",
          "Should be subtle enough not to distract from the overall interface",
          "Reversible when the pointer moves away"
        ]
      },
      "platforms": {
        "web": {
          "term": "hover",
          "notes": "CSS :hover pseudo-class",
          "reference": "https://developer.mozilla.org/en-US/docs/Web/CSS/:hover"
        },
        "iOS": {
          "term": "highlighted",
          "notes": "iOS uses 'highlighted' for similar visual feedback on touch devices with pointer support",
          "reference": "UIControl.State.highlighted"
        }
      },
      "terminology": {
        "conceptType": "term",
        "namingRationale": "Standard interaction design term describing pointer-based feedback"
      },
      "sources": [
        {
          "type": "industry-standard",
          "reference": "W3C CSS specification",
          "url": "https://www.w3.org/TR/selectors-4/#hover-pseudo",
          "date": "2025-01-12"
        }
      ],
      "governance": {
        "owner": "Spectrum Core Team",
        "reviewDate": "2025-01-12",
        "status": "approved"
      },
      "relatedTerms": ["default", "active", "focus"]
    },
    {
      "id": "active",
      "label": "Active",
      "description": "Active or pressed state",
      "usedIn": ["component-options", "component-schemas"]
    },
    {
      "id": "focus",
      "label": "Focus",
      "description": "Focused state (generic)",
      "usedIn": ["component-options", "component-schemas"]
    },
    {
      "id": "keyboard-focus",
      "label": "Keyboard Focus",
      "aliases": ["keyboard focus", "key-focus"],
      "description": "Focused via keyboard navigation",
      "usedIn": ["tokens", "component-options", "component-schemas"],
      "definition": {
        "superordinate": "interaction state",
        "description": "The state when a component receives focus through keyboard navigation, indicating it will respond to keyboard input",
        "essentialCharacteristics": [
          "Specifically indicates focus achieved through keyboard interaction (Tab, arrow keys)",
          "Requires prominent visual indicator for accessibility (WCAG 2.4.7)",
          "Different from generic focus to support :focus-visible patterns",
          "Critical for keyboard-only users to understand their current position"
        ]
      },
      "platforms": {
        "web": {
          "term": "keyboard-focus",
          "notes": "Often implemented with :focus-visible pseudo-class",
          "reference": "https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible"
        },
        "iOS": {
          "term": "focused",
          "notes": "UIFocusSystem for keyboard and pointer navigation",
          "reference": "UIFocusSystem"
        }
      },
      "terminology": {
        "conceptType": "term",
        "namingRationale": "Distinguishes keyboard-based focus from programmatic focus, following modern accessibility standards"
      },
      "sources": [
        {
          "type": "industry-standard",
          "reference": "WCAG 2.4.7 Focus Visible",
          "url": "https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html",
          "date": "2025-01-12"
        },
        {
          "type": "industry-standard",
          "reference": "W3C :focus-visible specification",
          "url": "https://www.w3.org/TR/selectors-4/#the-focus-visible-pseudo",
          "date": "2025-01-12"
        }
      ],
      "governance": {
        "owner": "Spectrum Core Team",
        "reviewDate": "2025-01-12",
        "status": "approved"
      },
      "relatedTerms": ["focus", "default", "hover"]
    },
    {
      "id": "disabled",
      "label": "Disabled",
      "description": "Disabled or inactive state",
      "usedIn": ["component-options", "component-schemas"]
    },
    {
      "id": "down",
      "label": "Down",
      "description": "Pressed or down state (mouse button down)",
      "usedIn": ["tokens", "component-schemas"]
    },
    {
      "id": "pending",
      "label": "Pending",
      "description": "Loading or pending state",
      "usedIn": ["tokens"]
    },
    {
      "id": "selected",
      "label": "Selected",
      "description": "Selected or chosen state",
      "usedIn": ["component-schemas"]
    },
    {
      "id": "drag-and-drop",
      "label": "Drag and Drop",
      "aliases": ["drag and drop"],
      "description": "Being dragged or drag target state",
      "usedIn": ["component-schemas"]
    }
  ]
}
"##;

pub(crate) const FIELD_ADVISORY_FIELDS: &[&str] = &["variant", "component", "structure", "substructure", "anatomy", "object", "orientation", "position", "size", "density", "shape", "state"];

pub(crate) fn build_registry_map(
) -> std::collections::HashMap<String, std::collections::HashSet<String>> {
    let mut map = std::collections::HashMap::new();
    map.insert("variant".to_string(), parse_registry(VARIANTS_JSON));
    map.insert("component".to_string(), parse_registry(COMPONENTS_JSON));
    map.insert("structure".to_string(), parse_registry(STRUCTURES_JSON));
    map.insert("substructure".to_string(), parse_registry(SUBSTRUCTURES_JSON));
    map.insert("anatomy".to_string(), parse_registry(ANATOMY_TERMS_JSON));
    map.insert("object".to_string(), parse_registry(TOKEN_OBJECTS_JSON));
    map.insert("orientation".to_string(), parse_registry(ORIENTATIONS_JSON));
    map.insert("position".to_string(), parse_registry(POSITIONS_JSON));
    map.insert("size".to_string(), parse_registry(SIZES_JSON));
    map.insert("density".to_string(), parse_registry(DENSITIES_JSON));
    map.insert("shape".to_string(), parse_registry(SHAPES_JSON));
    map.insert("state".to_string(), parse_registry(STATES_JSON));
    map
}
