// Copyright 2026 Adobe. All rights reserved.
// This file is licensed to you under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may obtain a copy
// of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under
// the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
// OF ANY KIND, either express or implied. See the License for the specific language
// governing permissions and limitations under the License.

//! Design system registry data embedded at compile time.
//!
//! Registry JSON files are embedded via the generated `registry_data.rs` (run
//! `moon run sdk:codegen` to regenerate). The set of embedded registries and the
//! list of SPEC-009 advisory fields are both driven by the field catalog in
//! `packages/design-data/fields/` — no Rust changes needed when adding a field.

use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

use serde_json::Value;

// ── Field catalog types ────────────────────────────────────────────────────

/// Validation severity for a name-object field, as declared in the fields/ catalog.
///
/// - `Advisory`: value must come from the registry vocab; violation is a warning (SPEC-009).
/// - `Strict`: value must come from the registry vocab; violation is a hard error.
/// - `None`: no registry-vocabulary check (e.g. numeric `scaleIndex`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FieldValidation {
    Advisory,
    Strict,
    None,
}

/// One field catalog entry — metadata for a single `packages/design-data/fields/*.json` file.
///
/// Generated by `sdk/scripts/generate-registry-data.js` and embedded at compile time
/// via `build_field_catalog()` in `registry_data.rs`.
#[derive(Debug, Clone)]
pub struct FieldCatalogEntry {
    /// Field key as used in name objects (e.g. `"variant"`, `"colorFamily"`).
    pub name: &'static str,
    /// `serialization.position` — controls name-object field order.
    pub position: u32,
    /// Registry validation severity.
    pub validation: FieldValidation,
    /// Domain scope restriction, or `None` for universal fields (SPEC-042).
    pub scope: Option<&'static str>,
    /// Whether this field is required on every name object.
    pub required: bool,
    /// Whether this field has an associated registry vocabulary.
    pub has_registry: bool,
    /// JSON value type: `"string"` or `"integer"`.
    pub value_type: &'static str,
}

/// The full fields/ catalog embedded at compile time.
///
/// Entries are ordered by `serialization.position`.  Built from
/// `packages/design-data/fields/*.json` via `moon run sdk:codegen`.
pub struct FieldCatalog {
    entries: Vec<FieldCatalogEntry>,
}

impl FieldCatalog {
    /// Return the catalog embedded at compile time (generated from `packages/design-data/fields/`).
    ///
    /// Initialised once via `OnceLock`; subsequent calls return the same allocation
    /// with no extra parsing or heap work.
    pub fn embedded() -> &'static Self {
        static INSTANCE: OnceLock<FieldCatalog> = OnceLock::new();
        INSTANCE.get_or_init(|| Self {
            entries: build_field_catalog(),
        })
    }

    /// Look up a catalog entry by field name.  Returns `None` if the key is not
    /// in the fields/ catalog.
    pub fn get(&self, name: &str) -> Option<&FieldCatalogEntry> {
        self.entries.iter().find(|e| e.name == name)
    }

    /// All entries in `serialization.position` order (ascending).
    pub fn entries_by_position(&self) -> &[FieldCatalogEntry] {
        &self.entries
    }
}

/// Parsed registry data for SPEC-009 enum validation and legacy-key serialization.
///
/// Keyed by field name (e.g. `"component"`, `"state"`). Built from the
/// field catalog declarations in `packages/design-data/fields/` via
/// the generated `build_registry_map()` and `build_token_name_map()` functions
/// in `registry_data.rs`.
#[derive(Debug, Clone)]
pub struct RegistryData {
    registries: HashMap<String, HashSet<String>>,
    /// Per-field id → tokenName map for legacy-key long-form expansion
    /// (e.g. size `"xl"` → `"extra-large"`).
    token_names: HashMap<String, HashMap<String, String>>,
}

/// Parse a registry JSON file into a set of value IDs (and their aliases).
fn parse_registry(json_str: &str) -> HashSet<String> {
    let v: Value = serde_json::from_str(json_str).expect("embedded registry JSON must be valid");
    let mut set = HashSet::new();
    if let Some(values) = v.get("values").and_then(|v| v.as_array()) {
        for entry in values {
            if let Some(id) = entry.get("id").and_then(|v| v.as_str()) {
                set.insert(id.to_string());
            }
            if let Some(aliases) = entry.get("aliases").and_then(|v| v.as_array()) {
                for alias in aliases {
                    if let Some(a) = alias.as_str() {
                        set.insert(a.to_string());
                    }
                }
            }
        }
    }
    set
}

/// Parse a registry JSON file into an id → tokenName map.
///
/// `tokenName` is the long-form alias used in legacy keys (e.g. size id `"xl"` →
/// tokenName `"extra-large"`). Entries without a `tokenName` field are omitted;
/// callers fall back to the raw id value.
fn parse_token_name_map(json_str: &str) -> HashMap<String, String> {
    let v: Value = serde_json::from_str(json_str).expect("embedded registry JSON must be valid");
    let mut map = HashMap::new();
    if let Some(values) = v.get("values").and_then(|v| v.as_array()) {
        for entry in values {
            if let (Some(id), Some(token_name)) = (
                entry.get("id").and_then(|v| v.as_str()),
                entry.get("tokenName").and_then(|v| v.as_str()),
            ) {
                map.insert(id.to_string(), token_name.to_string());
            }
        }
    }
    map
}

// Generated by scripts/generate-registry-data.js from the field catalog and
// registry JSON files. Checked into git so the crate is self-contained.
// Regenerate with: moon run sdk:codegen
include!("registry_data.rs");

impl RegistryData {
    /// Return registry data from the embedded JSON constants in `registry_data.rs`.
    ///
    /// `registry_data.rs` is generated from `packages/design-data/fields/`
    /// (field catalog) and `packages/design-data/registry/` (vocabulary)
    /// by running `moon run sdk:codegen`. Adding a new field declaration and
    /// re-running codegen is all that's needed to extend SPEC-009.
    ///
    /// Initialised once via `OnceLock` — the 21 `serde_json::from_str` calls in
    /// `build_registry_map` run only on the first call per process.
    pub fn embedded() -> &'static Self {
        static INSTANCE: OnceLock<RegistryData> = OnceLock::new();
        INSTANCE.get_or_init(|| Self {
            registries: build_registry_map(),
            token_names: build_token_name_map(),
        })
    }

    /// Look up the legacy-key long form for a registry value id.
    ///
    /// Returns `None` when the field has no tokenName expansion for `id`
    /// (the id is already the form used in legacy keys). Callers should
    /// fall back to the raw id value.
    ///
    /// Example: `token_name("size", "xl")` → `Some("extra-large")`
    pub fn token_name(&self, field: &str, id: &str) -> Option<&str> {
        self.token_names.get(field)?.get(id).map(String::as_str)
    }

    /// Look up the vocabulary set for a name-object field.
    /// Returns `None` for fields without a registry (e.g. mode-set fields).
    pub fn for_field(&self, field: &str) -> Option<&HashSet<String>> {
        self.registries.get(field)
    }

    /// The set of semantic fields that SPEC-009 checks against their registry.
    /// Derived from field declarations with `validation: "advisory"` and a registry.
    pub fn advisory_fields(&self) -> &[&str] {
        FIELD_ADVISORY_FIELDS
    }

    /// The set of valid component category ids from the categories registry.
    /// Used by SPEC-034 to validate `meta.category` on component declarations.
    pub fn categories(&self) -> &HashSet<String> {
        self.registries
            .get("categories")
            .expect("categories registry is always embedded")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_registries_load() {
        let r = RegistryData::embedded();
        assert!(r.for_field("component").unwrap().contains("button"));
        assert!(r.for_field("state").unwrap().contains("hover"));
        assert!(r.for_field("variant").unwrap().contains("accent"));
        assert!(r.for_field("size").unwrap().contains("m"));
        assert!(r.for_field("anatomy").unwrap().contains("icon"));
        assert!(r.for_field("object").unwrap().contains("background"));
        assert!(r.for_field("structure").unwrap().contains("base"));
        assert!(r.for_field("orientation").unwrap().contains("vertical"));
        assert!(r.for_field("position").unwrap().contains("top"));
        assert!(r.for_field("density").unwrap().contains("compact"));
        assert!(r.for_field("shape").unwrap().contains("uniform"));
    }

    #[test]
    fn sizes_excludes_numeric_scale() {
        let r = RegistryData::embedded();
        let sizes = r.for_field("size").unwrap();
        assert!(!sizes.contains("50"));
        assert!(!sizes.contains("100"));
        assert!(!sizes.contains("200"));
    }

    #[test]
    fn for_field_returns_correct_registry() {
        let r = RegistryData::embedded();
        assert!(r.for_field("component").unwrap().contains("button"));
        assert!(r.for_field("object").unwrap().contains("background"));
        assert!(r.for_field("property").unwrap().contains("color")); // advisory registry
        assert!(r.for_field("colorScheme").is_none()); // mode-set, validated by SPEC-005/008
    }

    #[test]
    fn advisory_fields_matches_catalog() {
        let r = RegistryData::embedded();
        let fields = r.advisory_fields();
        // All advisory fields must have a backing registry
        for &field in fields {
            assert!(
                r.for_field(field).is_some(),
                "advisory field '{field}' has no registry"
            );
        }
        // The expected set from the field catalog
        assert!(fields.contains(&"component"));
        assert!(fields.contains(&"state"));
        assert!(fields.contains(&"variant"));
        assert!(fields.contains(&"size"));
        assert!(fields.contains(&"property")); // advisory registry added in #941
                                               // mode-set fields must not appear
        assert!(!fields.contains(&"colorScheme"));
        assert!(!fields.contains(&"scale"));
        assert!(!fields.contains(&"contrast"));
    }
}
