// Copyright 2026 Adobe. All rights reserved.
// This file is licensed to you under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may obtain a copy
// of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under
// the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
// OF ANY KIND, either express or implied. See the License for the specific language
// governing permissions and limitations under the License.

//! Serialisable DTOs whose TypeScript types are auto-generated by `tsify-next`.

use serde::{Deserialize, Serialize};
use tsify_next::Tsify;
use wasm_bindgen::prelude::wasm_bindgen;

/// A single entry in a registry vocabulary (e.g. a size, state, or variant).
///
/// Mirrors the shape of each object in `registry/*.json#values`.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "camelCase")]
pub struct RegistryEntry {
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aliases: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deprecated: Option<bool>,
}

/// A registry vocabulary object as read from `registry/*.json`.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
pub struct RegistryObject {
    pub values: Vec<RegistryEntry>,
}

/// A token record as returned by query results.
///
/// Reflects `design_data_core::graph::TokenRecord` — the canonical token object
/// including its `name`, `value`, `uuid`, `$schema`, etc. in `raw`.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "camelCase")]
pub struct TokenResult {
    pub name: String,
    /// The token's full source JSON (all fields: name, value, uuid, $schema, etc.)
    pub raw: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub schema_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alias_target: Option<String>,
    pub layer: String,
}

/// A single resolved token result from `Dataset.resolve()`.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "camelCase")]
pub struct ResolveResult {
    pub token: TokenResult,
    pub specificity: u32,
}

/// Severity level of a validation diagnostic.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    Error,
    Warning,
    Info,
}

/// A single validation diagnostic.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "camelCase")]
pub struct Diagnostic {
    pub severity: Severity,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rule_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

/// The result of `Dataset.validate()`.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
pub struct ValidationResult {
    pub valid: bool,
    pub errors: Vec<Diagnostic>,
    pub warnings: Vec<Diagnostic>,
}

// ---------------------------------------------------------------------------
// Diff result types — typed mirrors of design_data_core::diff structs
//
// Using serde_json::Value inside a tsify struct causes serialization issues via
// serde-wasm-bindgen (nested map entries are silently dropped). Instead we
// define concrete typed structs here so every field survives the JS boundary.
// ---------------------------------------------------------------------------

/// A single key→value change within a token's properties.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "camelCase")]
pub struct PropertyChange {
    pub path: String,
    pub change_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub new_value: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub original_value: Option<serde_json::Value>,
}

/// A token that was renamed (same UUID, different name).
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "camelCase")]
pub struct RenamedToken {
    pub old_name: String,
    pub new_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    pub property_changes: Vec<PropertyChange>,
}

/// A token that was added.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "camelCase")]
pub struct AddedToken {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

/// A token that was deleted.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "camelCase")]
pub struct DeletedToken {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

/// A token that gained a `deprecated` marker.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "camelCase")]
pub struct DeprecatedToken {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

/// A token that had its `deprecated` marker removed.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "camelCase")]
pub struct RevertedToken {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

/// A token that had property-level changes (same name, same UUID).
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "camelCase")]
pub struct UpdatedToken {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    pub property_changes: Vec<PropertyChange>,
}

/// The result of `Dataset.diff()`.
///
/// Mirrors `design_data_core::diff::DiffReport` with typed arrays for each change category.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
pub struct DiffResult {
    pub renamed: Vec<RenamedToken>,
    pub deprecated: Vec<DeprecatedToken>,
    pub reverted: Vec<RevertedToken>,
    pub added: Vec<AddedToken>,
    pub deleted: Vec<DeletedToken>,
    pub updated: Vec<UpdatedToken>,
}

// ---------------------------------------------------------------------------
// Newtype wrappers for Vec<T> returns
//
// wasm-bindgen cannot directly express `Vec<T>` as `T[]` in TypeScript when T
// is a non-primitive struct. Adding tsify `into_wasm_abi` to a newtype lets
// wasm-pack generate the correct `T[]` annotation.
// ---------------------------------------------------------------------------

/// A list of token results from a query. Typed as `TokenResult[]` in TypeScript.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
pub struct TokenResultArray(Vec<TokenResult>);

impl TokenResultArray {
    pub fn new(v: Vec<TokenResult>) -> Self {
        Self(v)
    }
}

/// A single ranked suggestion result from `Dataset.suggest()`.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "camelCase")]
pub struct SuggestResult {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token_uuid: Option<String>,
    pub token_name: String,
    pub file: String,
    pub layer: String,
    pub confidence: f32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name_object: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
}

/// A list of suggestion results from `Dataset.suggest()`. Typed as `SuggestResult[]` in TypeScript.
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
pub struct SuggestResultArray(Vec<SuggestResult>);

impl SuggestResultArray {
    pub fn new(v: Vec<SuggestResult>) -> Self {
        Self(v)
    }
}

/// The result of `Dataset.resolveReference()`.
///
/// Contains the resolved terminal value and the full chain of names/references
/// traversed to reach it — mirrors the `getResolutionChain()` behaviour from
/// the legacy inline `TokenResolver` in `docs/s2-tokens-viewer/index.html`.
///
/// ```ts
/// const r = ds.resolveReference("{accent-color-100}", { colorScheme: "light" });
/// // r.chain → ["{accent-color-100}", "{blue-100}", "rgb(245, 249, 255)"]
/// // r.value → "rgb(245, 249, 255)"
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "camelCase")]
pub struct ReferenceChainResult {
    /// The resolved terminal value (absent if the chain is empty or all aliases dangle).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    /// Ordered list from original reference → intermediate names → final value string.
    pub chain: Vec<String>,
}

/// A mode-set context for token resolution.
///
/// Maps mode-set names (e.g. `"colorScheme"`, `"scale"`) to their active mode
/// values (e.g. `"dark"`, `"medium"`).
///
/// ```ts
/// const result = ds.resolve("background", { colorScheme: "dark", scale: "medium" });
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]
#[tsify(from_wasm_abi)]
pub struct ResolutionContext(std::collections::HashMap<String, String>);

impl ResolutionContext {
    pub fn into_inner(self) -> std::collections::HashMap<String, String> {
        self.0
    }
}

// ---------------------------------------------------------------------------
// Conversion helpers from core types
// ---------------------------------------------------------------------------

impl From<design_data_core::suggest::SuggestionResult> for SuggestResult {
    fn from(r: design_data_core::suggest::SuggestionResult) -> Self {
        Self {
            token_uuid: r.token_uuid,
            token_name: r.token_name,
            file: r.file.to_string_lossy().into_owned(),
            layer: format!("{:?}", r.layer).to_lowercase(),
            confidence: r.confidence,
            name_object: r.name_object,
            value: r.value,
        }
    }
}

impl From<&design_data_core::graph::TokenRecord> for TokenResult {
    fn from(r: &design_data_core::graph::TokenRecord) -> Self {
        Self {
            name: r.name.clone(),
            raw: r.raw.clone(),
            uuid: r.uuid.clone(),
            schema_url: r.schema_url.clone(),
            alias_target: r.alias_target.clone(),
            layer: format!("{:?}", r.layer).to_lowercase(),
        }
    }
}

impl From<&design_data_core::report::Severity> for Severity {
    fn from(s: &design_data_core::report::Severity) -> Self {
        match s {
            design_data_core::report::Severity::Error => Severity::Error,
            design_data_core::report::Severity::Warning => Severity::Warning,
            design_data_core::report::Severity::Info => Severity::Info,
        }
    }
}

impl From<&design_data_core::report::Diagnostic> for Diagnostic {
    fn from(d: &design_data_core::report::Diagnostic) -> Self {
        Self {
            severity: Severity::from(&d.severity),
            message: d.message.clone(),
            rule_id: d.rule_id.clone(),
            path: d.instance_path.clone().or_else(|| d.token.clone()),
        }
    }
}

impl From<design_data_core::report::ValidationReport> for ValidationResult {
    fn from(r: design_data_core::report::ValidationReport) -> Self {
        // NOTE: `ValidationReport.errors` holds ALL diagnostics regardless of severity
        // (there is no separate `warnings` field in the core type — see sdk/core/src/report.rs).
        // We split them into two JS-facing arrays by filtering the same slice twice; this is
        // intentional, not a bug.
        let errors = r
            .errors
            .iter()
            .filter(|d| {
                matches!(
                    d.severity,
                    design_data_core::report::Severity::Error
                )
            })
            .map(Diagnostic::from)
            .collect();
        let warnings = r
            .errors
            .iter()
            .filter(|d| {
                matches!(
                    d.severity,
                    design_data_core::report::Severity::Warning
                        | design_data_core::report::Severity::Info
                )
            })
            .map(Diagnostic::from)
            .collect();
        Self {
            valid: r.valid,
            errors,
            warnings,
        }
    }
}
